# Generated by Django 4.0.5 on 2022-07-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0003_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMemories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybapp.student')),
            ],
        ),
    ]
