# Generated by Django 4.0.5 on 2022-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0004_textmemories'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TextMemories',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
