# Generated by Django 4.0.5 on 2022-07-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybapp', '0005_studentgallery_remove_student_age_alter_student_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
